use_frameworks!

pre_install do |installer| Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}

end

target 'LKProvide_Tests' do
  pod 'LKProvide', :path => '../'
  
  
end
